enum DisplayState {
    DISCONNECTED = "DISCONNECTED",
    PRE_MINT = "PRE_MINT",
    PRIVATE_MINT = "PRIVATE_MINT",
    PRE_PUBLIC_MINT = "PRE_PUBLIC_MINT",
    PUBLIC_MINT = "PUBLIC_MINT",
    OBSOLETE = "OBSOLETE",
    PRE_REVEAL = "PRE_REVEAL",
    STAKING = "STAKING"
}

export default DisplayState;