enum DisplayState {
    PRE_MINT = "PRE_MINT",
    PRIVATE_MINT = "PRIVATE_MINT",
    PRE_PUBLIC_MINT = "PRE_PUBLIC_MINT",
    PUBLIC_MINT = "PUBLIC_MINT",
    MINT_FINISHED = "MINT_FINISHED",
    REVEALED = "REVEALED"
}

export default DisplayState;