enum DisplayState {
    DISCONNECTED = "DISCONNECTED",
    PRE_AUCTION = "PRE_AUCTION",
    PRIVATE_AUCTION = "PRIVATE_AUCTION",
    PRE_PUBLIC_AUCTION = "PRE_PUBLIC_AUCTION",
    PUBLIC_AUCTION = "PUBLIC_AUCTION",
    PRE_MINT = "PRE_MINT",
    PRE_REVEAL = "PRE_REVEAL",
    STAKING = "STAKING"
}

export default DisplayState;